In [10]:
import torch

# Example tensors a (m, 2) and b (n, 2)
a = torch.tensor([
  [1, 2],
  [3, 4],
  [5, 6],
  [7, 8],
  [9, 10]
])

b = torch.tensor([
  [3, 4],
  [9, 10],
  [7, 8],
  [7, 8],
])



In [19]:
from torch_scatter import scatter

indices = torch.where(torch.all(a[:, None] == b, dim=2))

print(indices)
print(indices[0])
scatter(indices[0], indices[1], dim=0)

(tensor([1, 3, 3, 4]), tensor([0, 2, 3, 1]))
tensor([1, 3, 3, 4])


tensor([1, 4, 3, 3])